/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janelas;

import ObjetoProcesso.PessoaFisica;
import ObjetoProcesso.PessoaJuridica;
import Processos.Arquivos;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author julio
 */
public class JanelaAdicionar extends javax.swing.JFrame {

    /**
     * Creates new form JanelaAdicionar
     */
    public JanelaAdicionar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInfos = new javax.swing.JLabel();
        lblNomeAutor = new javax.swing.JLabel();
        lblCpfCnpj = new javax.swing.JLabel();
        lblNomeAdvAutor = new javax.swing.JLabel();
        lblNomeReu = new javax.swing.JLabel();
        lblNomeAdvReu = new javax.swing.JLabel();
        lblNumProc = new javax.swing.JLabel();
        tbxCpfCnpj = new javax.swing.JTextField();
        tbxAutor = new javax.swing.JTextField();
        tbxAdvReu = new javax.swing.JTextField();
        tbxNumProc = new javax.swing.JTextField();
        tbxAdvAutor = new javax.swing.JTextField();
        tbxReu = new javax.swing.JTextField();
        btnCpf = new javax.swing.JButton();
        btnCnpj = new javax.swing.JButton();
        lblAvisoSucesso = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblInfos.setText("informe os dados para cadastrar o processo");

        lblNomeAutor.setText("nome do autor");

        lblCpfCnpj.setText("cpf ou cnpj");

        lblNomeAdvAutor.setText("nome do advogado do autor");

        lblNomeReu.setText("nome do reu");

        lblNomeAdvReu.setText("nome do advogado do reu");

        lblNumProc.setText("numero do processo");

        btnCpf.setText("adicionar pessoa fisica");
        btnCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCpfActionPerformed(evt);
            }
        });

        btnCnpj.setText("adicionar pessoa juridica");
        btnCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCnpjActionPerformed(evt);
            }
        });

        lblAvisoSucesso.setText(".");

        jButton1.setForeground(new java.awt.Color(240, 0, 0));
        jButton1.setText("VOLTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(lblInfos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCpf)
                    .addComponent(lblNomeReu)
                    .addComponent(lblNomeAdvAutor)
                    .addComponent(lblCpfCnpj)
                    .addComponent(lblNomeAutor)
                    .addComponent(lblNomeAdvReu)
                    .addComponent(lblNumProc))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tbxNumProc, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                        .addComponent(tbxAdvReu)
                        .addComponent(tbxReu)
                        .addComponent(tbxCpfCnpj)
                        .addComponent(tbxAdvAutor)
                        .addComponent(tbxAutor)
                        .addComponent(btnCnpj, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblAvisoSucesso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(92, 92, 92))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInfos)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbxAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeAutor))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbxCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCpfCnpj))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbxAdvAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeAdvAutor))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbxReu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeReu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbxAdvReu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeAdvReu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbxNumProc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumProc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAvisoSucesso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCnpj)
                    .addComponent(btnCpf))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(26, 26, 26))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblCpfCnpj, lblNomeAdvAutor, lblNomeAdvReu, lblNomeAutor, lblNomeReu, lblNumProc});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCpfActionPerformed
        String nomeAutor = tbxAutor.getText();
        String cpf = tbxCpfCnpj.getText();
        String advAutor = tbxAdvAutor.getText();
        String nomeReu = tbxReu.getText();
        String advReu = tbxAdvReu.getText();
        String numProc = tbxNumProc.getText();
        PessoaFisica pessoa = new PessoaFisica(nomeReu,nomeAutor,numProc,advAutor,advReu,cpf);
        try {
            Arquivos.AdicionaProcesso(pessoa, Arquivos.tamanhoArquivo());
        } catch (IOException ex) {
            System.out.println("Erro ao adicionar Processo");
        }
        lblAvisoSucesso.setText("Pessoa Fisica adicionada com sucesso!");
    }//GEN-LAST:event_btnCpfActionPerformed

    private void btnCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCnpjActionPerformed
        String nomeAutor = tbxAutor.getText();
        String cnpj = tbxCpfCnpj.getText();
        String advAutor = tbxAdvAutor.getText();
        String nomeReu = tbxReu.getText();
        String advReu = tbxAdvReu.getText();
        String numProc = tbxNumProc.getText();
        PessoaJuridica empresa = new PessoaJuridica(nomeReu,nomeAutor,numProc,advAutor,advReu,cnpj);
        try {
            Arquivos.AdicionaProcesso(empresa, Arquivos.tamanhoArquivo());
        } catch (IOException ex) {
            System.out.println("Erro ao adicionar pessoa");
        }
        lblAvisoSucesso.setText("Pessoa Juridica adicionada com sucesso!");
    }//GEN-LAST:event_btnCnpjActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaAdicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaAdicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaAdicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaAdicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaAdicionar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCnpj;
    private javax.swing.JButton btnCpf;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblAvisoSucesso;
    private javax.swing.JLabel lblCpfCnpj;
    private javax.swing.JLabel lblInfos;
    private javax.swing.JLabel lblNomeAdvAutor;
    private javax.swing.JLabel lblNomeAdvReu;
    private javax.swing.JLabel lblNomeAutor;
    private javax.swing.JLabel lblNomeReu;
    private javax.swing.JLabel lblNumProc;
    private javax.swing.JTextField tbxAdvAutor;
    private javax.swing.JTextField tbxAdvReu;
    private javax.swing.JTextField tbxAutor;
    private javax.swing.JTextField tbxCpfCnpj;
    private javax.swing.JTextField tbxNumProc;
    private javax.swing.JTextField tbxReu;
    // End of variables declaration//GEN-END:variables
}
